'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const path=require('node:path');const fs=require('node:fs');
const {normalizeLinkedInUrl}=require('../src/utils/normalizeUrl');
const {seamlessCredential}=require('../src/config/credentials');
const {SeamlessRestClient,SeamlessRestError}=require('../src/seamless/restClient');
const {EnrichmentService,researchKey}=require('../src/http/enrichment');
const {createHandler}=require('../src/server/app');
class MemoryStore{constructor(){this.jobs=new Map();this.people=new Set();this.claims=0}async ready(){}async ensurePerson(u){this.people.add(u)}async getResearch(k){return this.jobs.get(k)||null}async researchForPerson(){return[]}async claimResearch(k,u,p){if(this.jobs.has(k))return false;this.jobs.set(k,structuredClone(p));this.claims++;return true}async saveResearch(k,p){if(!this.jobs.has(k))throw Error('missing');this.jobs.set(k,structuredClone(p))}async deleteResearch(k){this.jobs.delete(k)}}
const cfg={apiBaseUrl:'https://api.seamless.ai/api/client/v1',requestTimeoutMs:30000,pollIntervalMs:2500,maxPolls:30};

test('normalizes a LinkedIn person URL',()=>assert.equal(normalizeLinkedInUrl('https://linkedin.com/in/Jane.Smith?x=1'),'https://www.linkedin.com/in/Jane.Smith/'));
test('rejects non-person LinkedIn URLs',()=>assert.throws(()=>normalizeLinkedInUrl('https://www.linkedin.com/company/acme'),/profile URL/));
test('credential selection prefers SEAMLESS_API_KEY then primary fallback',()=>{assert.deepEqual(seamlessCredential({SEAMLESS_API_KEY:' a ',SEAMLESS_API_KEY_PRIMARY:'b'}),{source:'SEAMLESS_API_KEY',key:'a'});assert.deepEqual(seamlessCredential({SEAMLESS_API_KEY_PRIMARY:' b '}),{source:'SEAMLESS_API_KEY_PRIMARY',key:'b'})});
test('explicit credential source is honored',()=>assert.deepEqual(seamlessCredential({SEAMLESS_KEY_SOURCE:'SEAMLESS_API_KEY_PRIMARY',SEAMLESS_API_KEY:'a',SEAMLESS_API_KEY_PRIMARY:'b'}),{source:'SEAMLESS_API_KEY_PRIMARY',key:'b'}));

test('direct research sends documented liProfileUrl body, Token header, and keeps dedupe enabled',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({success:true,requestIds:['r1']}),{status:202,headers:{'X-PublicAPI-Credits':'57','Content-Type':'application/json'}})};const c=new SeamlessRestClient('secret','https://api.seamless.ai/api/client/v1',1000,fetchMock);const r=await c.researchLinkedIn('https://www.linkedin.com/in/jane/');assert.equal(call.url,'https://api.seamless.ai/api/client/v1/contacts/research');assert.equal(call.init.headers.Token,'secret');assert.deepEqual(JSON.parse(call.init.body),{contacts:[{liProfileUrl:'https://www.linkedin.com/in/jane/'}],skipDeduplicationCheck:false});assert.equal(r.creditsRemaining,57)});

test('credits probe is a no-research GET /contacts and parses provider headers',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({data:[]}),{status:200,headers:{'X-PublicAPI-Credits':'123','X-RateLimit-Remaining':'41','X-RateLimit-Reset':'999'}})};const c=new SeamlessRestClient('secret','https://api.test/v1',1000,fetchMock);const r=await c.getCredits();assert.match(call.url,/\/contacts\?page=1&limit=1$/);assert.equal(call.init.method,'GET');assert.ok(!call.url.includes('research'));assert.deepEqual(r,{creditsRemaining:123,rateLimitRemaining:41,rateLimitReset:999})});

test('poll uses returned request IDs as comma-separated query',async()=>{let url;const c=new SeamlessRestClient('x','https://api.test/v1',1000,async(u)=>{url=String(u);return new Response(JSON.stringify({success:true,data:[]}),{status:200})});await c.pollContactResearch(['a','b']);assert.equal(url,'https://api.test/v1/contacts/research/poll?requestIds=a%2Cb')});

test('lookup checks saved result without calling provider',async()=>{const store=new MemoryStore();const url='https://www.linkedin.com/in/jane/';const key=researchKey(url);store.jobs.set(key,{mode:'direct-linkedin-rest',status:'done',normalizedUrl:url,researchKey:key,createdAt:1,data:{fullName:'Jane',linkedinUrl:url}});let calls=0;const rest={researchLinkedIn:async()=>{calls++},getCredits:async()=>({creditsRemaining:9})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup(url);assert.equal(r.cached,true);assert.equal(r.job.data.fullName,'Jane');assert.equal(calls,0)});

test('two concurrent starts result in one provider research submission',async()=>{const store=new MemoryStore();let calls=0;let release;const gate=new Promise(r=>release=r);const rest={researchLinkedIn:async()=>{calls++;await gate;return{data:{requestIds:['req']},creditsRemaining:8}},getCredits:async()=>({creditsRemaining:8})};const svc=new EnrichmentService(cfg,store,rest);const url='https://www.linkedin.com/in/jane/';const p1=svc.startResearch(url);await new Promise(r=>setImmediate(r));const p2=svc.startResearch(url);release();const [a,b]=await Promise.all([p1,p2]);assert.equal(calls,1);assert.ok(['submitting','processing'].includes(b.status));assert.equal(a.status,'processing')});

test('definitive 422 rejection releases claim so operator can retry later',async()=>{const store=new MemoryStore();let calls=0;const rest={researchLinkedIn:async()=>{calls++;if(calls===1)throw new SeamlessRestError(422,'insufficientCredits','no credits');return{data:{requestIds:['ok']},creditsRemaining:5}},getCredits:async()=>({creditsRemaining:5})};const svc=new EnrichmentService(cfg,store,rest);const url='https://www.linkedin.com/in/jane/';await assert.rejects(()=>svc.startResearch(url),/no credits/);assert.equal(store.jobs.size,0);const r=await svc.startResearch(url);assert.equal(r.status,'processing');assert.equal(calls,2)});

test('uncertain timeout is saved for review and never auto-resubmitted',async()=>{const store=new MemoryStore();let calls=0;const rest={researchLinkedIn:async()=>{calls++;throw new SeamlessRestError(504,'TIMEOUT','timeout')},getCredits:async()=>({creditsRemaining:5})};const svc=new EnrichmentService(cfg,store,rest);const url='https://www.linkedin.com/in/jane/';await assert.rejects(()=>svc.startResearch(url),/timeout/);const second=await svc.startResearch(url);assert.equal(second.status,'needs_review');assert.equal(calls,1)});

test('poll done normalizes Seamless contact fields and caches them',async()=>{const store=new MemoryStore();const url='https://www.linkedin.com/in/jane/';const key=researchKey(url);store.jobs.set(key,{mode:'direct-linkedin-rest',status:'processing',normalizedUrl:url,researchKey:key,createdAt:1,requestIds:['req']});const rest={pollContactResearch:async()=>({creditsRemaining:7,data:{data:[{requestId:'req',status:'done',contact:{fullName:'Jane Smith',email:'jane@example.com',contactPhone1:'+1555',company:'Acme',title:'Director',lIProfileUrl:url}}]}}),getCredits:async()=>({creditsRemaining:7})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.pollResearch(url);assert.equal(r.status,'done');assert.equal(r.data.email,'jane@example.com');assert.equal(r.data.phone,'+1555');assert.equal((await store.getResearch(key)).status,'done')});

test('duplicate poll status without contact is terminal and not resubmitted',async()=>{const store=new MemoryStore();const url='https://www.linkedin.com/in/jane/';const key=researchKey(url);store.jobs.set(key,{mode:'direct-linkedin-rest',status:'processing',normalizedUrl:url,researchKey:key,createdAt:1,requestIds:['req']});let researchCalls=0;const rest={pollContactResearch:async()=>({creditsRemaining:7,data:{data:[{requestId:'req',status:'duplicate',message:'already researched'}]}}),researchLinkedIn:async()=>{researchCalls++},getCredits:async()=>({creditsRemaining:7})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.pollResearch(url);assert.equal(r.status,'duplicate');await svc.startResearch(url);assert.equal(researchCalls,0)});

test('status reports REST architecture, no MCP requirement, and exact provider credits',async()=>{const store=new MemoryStore();const svc=new EnrichmentService(cfg,store,{getCredits:async()=>({creditsRemaining:44,rateLimitRemaining:59,rateLimitReset:1})});const r=await svc.status();assert.equal(r.seamless.transport,'REST');assert.equal(r.seamless.mcpRequired,false);assert.equal(r.credits.creditsRemaining,44)});

test('HTTP workspace is protected and lookup route uses injected service',async()=>{const fake={lookup:async u=>({linkedinUrl:u,job:null,readyToEnrich:true}),status:async()=>({database:{status:'READY'},seamless:{status:'READY'}}),ready:async()=>{}};const old=process.env.APP_AUTH_TOKEN;process.env.APP_AUTH_TOKEN='pw';const server=http.createServer(createHandler(fake));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await fetch(base+'/workspace')).status,401);const login=await fetch(base+'/auth/login',{method:'POST',headers:{Authorization:'Bearer pw'}});assert.equal(login.status,200);const lookup=await fetch(base+'/v1/person/lookup',{method:'POST',headers:{Authorization:'Bearer pw','Content-Type':'application/json'},body:JSON.stringify({linkedinUrl:'https://www.linkedin.com/in/jane/'})});assert.equal(lookup.status,200);assert.equal((await lookup.json()).readyToEnrich,true)}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.APP_AUTH_TOKEN;else process.env.APP_AUTH_TOKEN=old}});

test('verified build fingerprint matches current source',()=>{const {sourceHash}=require('../scripts-build-info.cjs');const info=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/BUILD_INFO.json'),'utf8'));assert.equal(info.version,'31.0.0');assert.equal(info.sourceHash,sourceHash())});
