'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {normalizeLinkedInUrl}=require('../src/utils/normalizeUrl');
const {SeamlessRestClient,SeamlessRestError}=require('../src/seamless/restClient');
const {EnrichmentService,researchKey,parseContact,companyCheck}=require('../src/http/enrichment');
const {SeamlessRoutePool}=require('../src/seamless/routePool');
const {seamlessCredentials}=require('../src/config/credentials');
const {createHandler}=require('../src/server/app');

const cfg={apiBaseUrl:'https://api.seamless.ai/api/client/v1',requestTimeoutMs:30000,pollIntervalMs:2500,maxPolls:30};
class MemoryStore{
  constructor(){this.people=new Set();this.jobs=new Map()}
  async ready(){}
  async ensurePerson(url){this.people.add(url)}
  async getResearch(id){return this.jobs.get(id)||null}
  async researchForPerson(url){return [...this.jobs.values()].filter(x=>x.normalizedUrl===url)}
  async claimResearch(id,url,payload){if(this.jobs.has(id))return false;this.jobs.set(id,{...payload});return true}
  async saveResearch(id,payload){if(!this.jobs.has(id))throw new Error('missing');this.jobs.set(id,{...payload})}
  async deleteResearch(id){this.jobs.delete(id)}
}
function response(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json',...headers}})}

test('normalizes exact LinkedIn person URLs',()=>{assert.equal(normalizeLinkedInUrl('https://linkedin.com/in/Jane-Smith?trk=x'),'https://www.linkedin.com/in/Jane-Smith/');assert.throws(()=>normalizeLinkedInUrl('https://linkedin.com/company/acme'),/LinkedIn/)});

test('direct research submits exactly one liProfileUrl and keeps deduplication enabled',async()=>{let seen;const client=new SeamlessRestClient('key',cfg.apiBaseUrl,30000,async(url,init)=>{seen={url,init};return response({success:true,requestIds:['req1']},202,{'X-PublicAPI-Credits':'9'})});await client.researchLinkedIn('https://www.linkedin.com/in/jane/');assert.match(seen.url,/\/contacts\/research$/);assert.equal(seen.init.headers.Token,'key');const body=JSON.parse(seen.init.body);assert.deepEqual(body,{contacts:[{liProfileUrl:'https://www.linkedin.com/in/jane/'}],skipDeduplicationCheck:false});assert.equal(body.contacts.length,1)});

test('lookup is provider-free: cache check only and no Seamless call',async()=>{const store=new MemoryStore();let calls=0;const rest={getCredits:async()=>{calls++;return{creditsRemaining:10}},researchLinkedIn:async()=>{calls++;throw Error('not expected')}};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup('https://www.linkedin.com/in/jane-smith/','Acme');assert.equal(r.readyToResearch,true);assert.equal(r.researchPlan.contacts,1);assert.equal(r.researchPlan.searchEndpointsUsed,false);assert.equal(calls,0)});

test('cached lookup returns contact without any provider request',async()=>{const store=new MemoryStore(),url=normalizeLinkedInUrl('https://linkedin.com/in/jane/'),key=researchKey(url);store.jobs.set(key,{status:'done',normalizedUrl:url,data:{fullName:'Jane',company:'Acme',jobHistory:[]}});let calls=0;const svc=new EnrichmentService(cfg,store,{getCredits:async()=>{calls++;return{creditsRemaining:9}}});const r=await svc.lookup(url,'Acme');assert.equal(r.cached,true);assert.equal(r.job.companyCheck.status,'current');assert.equal(calls,0)});

test('one enrichment action creates only one provider research submission',async()=>{const store=new MemoryStore();let researchCalls=0;const rest={getCredits:async()=>({creditsRemaining:10,observedAt:'before'}),researchLinkedIn:async url=>{researchCalls++;assert.equal(url,'https://www.linkedin.com/in/jane/');return{creditsRemaining:9,observedAt:'after',data:{requestIds:['req1']}}}};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/',targetCompany:'Acme'});assert.equal(researchCalls,1);assert.equal(r.requestIds.length,1);assert.equal(r.creditDelta,1);assert.equal(r.submittedContacts,1);assert.equal(r.maxAutomaticResearchSubmissions,1)});

test('concurrent clicks cannot submit the same LinkedIn profile twice',async()=>{const store=new MemoryStore();let calls=0;const rest={getCredits:async()=>({creditsRemaining:10}),researchLinkedIn:async()=>{calls++;await new Promise(r=>setTimeout(r,20));return{creditsRemaining:9,data:{requestIds:['req']}}}};const svc=new EnrichmentService(cfg,store,rest);const [a,b]=await Promise.all([svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'}),svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'})]);assert.equal(calls,1);assert.ok(['submitting','processing'].includes(a.status));assert.ok(['submitting','processing'].includes(b.status))});

test('ambiguous transport failure is never automatically resubmitted',async()=>{const store=new MemoryStore();let calls=0;const rest={getCredits:async()=>({creditsRemaining:10}),researchLinkedIn:async()=>{calls++;throw new Error('socket reset after send')}};const svc=new EnrichmentService(cfg,store,rest);await assert.rejects(()=>svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'}),/socket reset/);const saved=await store.getResearch(researchKey('https://www.linkedin.com/in/jane/'));assert.equal(saved.status,'needs_review');await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(calls,1)});

test('unexpected multiple request IDs are quarantined instead of polled automatically',async()=>{const store=new MemoryStore();const rest={getCredits:async()=>({creditsRemaining:10}),researchLinkedIn:async()=>({creditsRemaining:8,data:{requestIds:['a','b']}})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(r.status,'needs_review');assert.match(r.message,/2 request IDs/);assert.equal(r.creditAnomaly,true)});

test('poll parses current company and job history and measures one-credit delta',async()=>{const store=new MemoryStore(),url='https://www.linkedin.com/in/jane/';let creditCalls=0;const rest={getCredits:async()=>({creditsRemaining:creditCalls++===0?10:9,observedAt:'fresh'}),researchLinkedIn:async()=>({creditsRemaining:9,observedAt:'accepted',data:{requestIds:['req']}}),pollContactResearch:async ids=>{assert.deepEqual(ids,['req']);return{creditsRemaining:9,observedAt:'poll',data:{data:[{requestId:'req',status:'done',contact:{fullName:'Jane Smith',email:'jane@newco.com',company:'NewCo',title:'VP Sales',lIProfileUrl:url,formerCompany:'Acme',formerTitle:'Sales Director',jobHistory:[{companyName:'Acme',title:'Sales Director',startedAt:'2020-01-01T00:00:00Z',endedAt:'2024-01-01T00:00:00Z'}]}}]}}}};const svc=new EnrichmentService(cfg,store,rest);await svc.startResearch({linkedinUrl:url,targetCompany:'Acme'});const r=await svc.pollResearch({linkedinUrl:url});assert.equal(r.status,'done');assert.equal(r.data.company,'NewCo');assert.equal(r.companyCheck.status,'former');assert.equal(r.creditDelta,1);assert.equal(r.data.jobHistory[0].companyName,'Acme')});

test('target company check distinguishes current, former, and mismatch',()=>{const d={company:'NewCo',jobHistory:[{companyName:'Acme',title:'Director'}]};assert.equal(companyCheck(d,'NewCo').status,'current');assert.equal(companyCheck(d,'Acme').status,'former');assert.equal(companyCheck(d,'Other Corp').status,'mismatch')});

test('duplicate poll with returned contact is saved as done without a new submit',async()=>{const store=new MemoryStore(),url='https://www.linkedin.com/in/jane/';let submit=0;const rest={getCredits:async()=>({creditsRemaining:10}),researchLinkedIn:async()=>{submit++;return{creditsRemaining:10,data:{requestIds:['req']}}},pollContactResearch:async()=>({creditsRemaining:10,data:{data:[{requestId:'req',status:'duplicate',contact:{fullName:'Jane',company:'Acme',lIProfileUrl:url}}]}})};const svc=new EnrichmentService(cfg,store,rest);await svc.startResearch({linkedinUrl:url});const r=await svc.pollResearch({linkedinUrl:url});assert.equal(r.status,'done');assert.equal(r.providerStatus,'duplicate');assert.equal(submit,1)});

test('credit anomaly is explicit if provider balance drops by more than one',async()=>{const store=new MemoryStore();let creditCalls=0;const rest={getCredits:async()=>({creditsRemaining:creditCalls++===0?100:71}),researchLinkedIn:async()=>({creditsRemaining:71,data:{requestIds:['req']}}),pollContactResearch:async()=>({creditsRemaining:71,data:{data:[{requestId:'req',status:'done',contact:{fullName:'Jane',company:'Acme'}}]}})};const svc=new EnrichmentService(cfg,store,rest);const started=await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(started.creditDelta,29);assert.equal(started.creditAnomaly,true);const done=await svc.pollResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(done.creditAnomaly,true);assert.equal(done.creditDelta,29)});

test('multi-org route selection chooses one organization only and pins polling to it',async()=>{const store=new MemoryStore();let pSubmit=0,sSubmit=0,sPoll=0;const primary={getCredits:async()=>({creditsRemaining:3}),researchLinkedIn:async()=>{pSubmit++;throw Error('wrong route')}};const secondary={getCredits:async()=>({creditsRemaining:20}),researchLinkedIn:async()=>{sSubmit++;return{creditsRemaining:19,data:{requestIds:['sreq']}}},pollContactResearch:async()=>{sPoll++;return{creditsRemaining:19,data:{data:[{requestId:'sreq',status:'done',contact:{fullName:'Jane',company:'Acme'}}]}}}};const routes=[{id:'primary',source:'SEAMLESS_API_KEY_PRIMARY',rest:primary,client:primary},{id:'secondary',source:'SEAMLESS_API_KEY_SECONDARY',rest:secondary,client:secondary}];const pool={size:2,routes,routeMap:new Map(routes.map(r=>[r.id,r])),assertUniqueEgress:async()=>true,chooseResearchRoute:async()=>routes[1],status:async()=>({status:'READY',organizationCount:2,totalCreditsRemaining:23,routes:[]})};const svc=new EnrichmentService(cfg,store,null,pool);const started=await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(started.routeId,'secondary');assert.equal(pSubmit,0);assert.equal(sSubmit,1);await svc.pollResearch({linkedinUrl:'https://www.linkedin.com/in/jane/'});assert.equal(sPoll,1);assert.equal(pSubmit,0)});

test('status declares exact single-research architecture with contact search disabled',async()=>{const store=new MemoryStore();const svc=new EnrichmentService(cfg,store,{getCredits:async()=>({creditsRemaining:44,observedAt:'now'})});const r=await svc.status();assert.equal(r.architecture,'exact-linkedin-single-research');assert.equal(r.seamless.contactSearchDisabled,true);assert.equal(r.seamless.mcpRequired,false);assert.equal(r.seamless.maxAutomaticResearchSubmissions,1)});

test('multi-org credentials bind each key to its own deterministic egress proxy',()=>{const r=seamlessCredentials({SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://proxy-a:8080',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://proxy-b:8080',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'});assert.equal(r.routes.length,2);assert.deepEqual(r.routes.map(x=>[x.id,x.proxyUrl]),[['primary','http://proxy-a:8080'],['secondary','http://proxy-b:8080']])});

test('route pool sums distinct organization credits and verifies distinct egress IPs',async()=>{const env={SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://a:1',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://b:2',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'};const data={primary:{credits:12,ip:'203.0.113.10'},secondary:{credits:7,ip:'203.0.113.11'}};const pool=new SeamlessRoutePool(cfg,env,route=>({getCredits:async()=>({creditsRemaining:data[route.id].credits,observedAt:'now'}),getEgressIp:async()=>({ip:data[route.id].ip,observedAt:'now'})}));const st=await pool.status();assert.equal(st.totalCreditsRemaining,19);assert.equal(st.uniqueEgressVerified,true)});

test('fresh credit totals never substitute a stale previous balance',async()=>{let calls=0;const pool=new SeamlessRoutePool(cfg,{SEAMLESS_API_KEY_PRIMARY:'p'},()=>({getCredits:async()=>{calls++;return calls===1?{creditsRemaining:12,observedAt:'first'}:{creditsRemaining:null,observedAt:'second'}},getEgressIp:async()=>({ip:'203.0.113.10'})}));assert.equal((await pool.status()).totalCreditsRemaining,12);const second=await pool.status();assert.equal(second.totalCreditsRemaining,null);assert.equal(second.routes[0].lastKnownCreditsRemaining,12)});

test('HTTP research accepts target company but exposes no searchResultId flow',async()=>{let input;const fake={lookup:async(u,t)=>({linkedinUrl:u,targetCompany:t,readyToResearch:true}),startResearch:async i=>(input=i,{status:'processing'}),pollResearch:async()=>({status:'done'}),status:async()=>({database:{status:'READY'},seamless:{status:'READY'}}),ready:async()=>{}};const old=process.env.APP_AUTH_TOKEN;process.env.APP_AUTH_TOKEN='pw';const server=http.createServer(createHandler(fake));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{const res=await fetch(base+'/v1/person/research',{method:'POST',headers:{Authorization:'Bearer pw','Content-Type':'application/json'},body:JSON.stringify({linkedinUrl:'https://www.linkedin.com/in/jane/',targetCompany:'Acme',searchResultId:'should-be-ignored'})});assert.equal(res.status,202);assert.equal(input.targetCompany,'Acme');assert.equal(Object.hasOwn(input,'searchResultId'),false)}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.APP_AUTH_TOKEN;else process.env.APP_AUTH_TOKEN=old}});

test('production runtime contains no contact search or MCP client',()=>{const files=['../src/http/enrichment.js','../src/seamless/restClient.js','../src/seamless/routePool.js','../src/server/app.js'];const joined=files.map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');assert.equal(joined.includes('/search/contacts'),false);assert.equal(joined.includes('search_contacts'),false);assert.equal(joined.includes('McpClient'),false);assert.equal(fs.existsSync(path.join(__dirname,'../src/seamless/mcpClient.js')),false)});

test('verified build fingerprint matches v36 source',()=>{const {sourceHash}=require('../scripts-build-info.cjs');const info=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/BUILD_INFO.json'),'utf8'));assert.equal(info.version,'36.0.0');assert.equal(info.sourceHash,sourceHash())});
