'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
const {normalizeLinkedInUrl}=require('../src/utils/normalizeUrl');
const {seamlessCredential,seamlessCredentials}=require('../src/config/credentials');
const {SeamlessRestClient,SeamlessRestError}=require('../src/seamless/restClient');
const {SeamlessRoutePool}=require('../src/seamless/routePool');
const {EnrichmentService,researchKey,inferNameFromLinkedInUrl}=require('../src/http/enrichment');
const {createHandler}=require('../src/server/app');
class MemoryStore{constructor(){this.jobs=new Map();this.people=new Set();this.claims=0}async ready(){}async ensurePerson(u){this.people.add(u)}async getResearch(k){return this.jobs.get(k)||null}async researchForPerson(u){return[...this.jobs.values()].filter(j=>j.normalizedUrl===u)}async claimResearch(k,u,p){if(this.jobs.has(k))return false;this.jobs.set(k,structuredClone(p));this.claims++;return true}async saveResearch(k,p){if(!this.jobs.has(k))throw Error('missing');this.jobs.set(k,structuredClone(p))}async deleteResearch(k){this.jobs.delete(k)}}
const cfg={apiBaseUrl:'https://api.seamless.ai/api/client/v1',requestTimeoutMs:30000,pollIntervalMs:2500,maxPolls:30};

test('normalizes a LinkedIn person URL',()=>assert.equal(normalizeLinkedInUrl('https://linkedin.com/in/Jane.Smith?x=1'),'https://www.linkedin.com/in/Jane.Smith/'));
test('rejects non-person LinkedIn URLs',()=>assert.throws(()=>normalizeLinkedInUrl('https://www.linkedin.com/company/acme'),/profile URL/));
test('infers a searchable full name from a normal LinkedIn slug',()=>assert.equal(inferNameFromLinkedInUrl('https://www.linkedin.com/in/taylor-gonsalves-b9b18b196/'),'Taylor Gonsalves'));
test('does not invent a name from an opaque LinkedIn slug',()=>assert.equal(inferNameFromLinkedInUrl('https://www.linkedin.com/in/tgonsalves123/'),null));
test('credential selection prefers SEAMLESS_API_KEY then primary fallback',()=>{assert.deepEqual(seamlessCredential({SEAMLESS_API_KEY:' a ',SEAMLESS_API_KEY_PRIMARY:'b'}),{source:'SEAMLESS_API_KEY',key:'a',proxyUrl:null});assert.deepEqual(seamlessCredential({SEAMLESS_API_KEY_PRIMARY:' b '}),{source:'SEAMLESS_API_KEY_PRIMARY',key:'b',proxyUrl:null})});

test('free discovery sends documented fullName contact-search body',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({data:[{searchResultId:'s1',name:'Jane Smith',company:'Acme'}]}),{status:200,headers:{'X-PublicAPI-Credits':'57','Content-Type':'application/json'}})};const c=new SeamlessRestClient('secret','https://api.seamless.ai/api/client/v1',1000,fetchMock);const r=await c.searchContactsByName('Jane Smith',50);assert.equal(call.url,'https://api.seamless.ai/api/client/v1/search/contacts');assert.equal(call.init.headers.Token,'secret');assert.deepEqual(JSON.parse(call.init.body),{nextToken:null,limit:50,fullName:['Jane Smith']});assert.equal(r.creditsRemaining,57)});

test('selected candidate research sends searchResultIds only',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({success:true,requestIds:['r1']}),{status:202,headers:{'X-PublicAPI-Credits':'56','Content-Type':'application/json'}})};const c=new SeamlessRestClient('secret','https://api.seamless.ai/api/client/v1',1000,fetchMock);await c.researchSearchResult('s1');assert.equal(call.url,'https://api.seamless.ai/api/client/v1/contacts/research');assert.deepEqual(JSON.parse(call.init.body),{searchResultIds:['s1']})});

test('direct LinkedIn research remains as explicit fallback with dedupe enabled',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({success:true,requestIds:['r1']}),{status:202,headers:{'X-PublicAPI-Credits':'55','Content-Type':'application/json'}})};const c=new SeamlessRestClient('secret','https://api.seamless.ai/api/client/v1',1000,fetchMock);await c.researchLinkedIn('https://www.linkedin.com/in/jane/');assert.deepEqual(JSON.parse(call.init.body),{contacts:[{liProfileUrl:'https://www.linkedin.com/in/jane/'}],skipDeduplicationCheck:false})});

test('credits probe uses valid ISO dates and parses provider balance header',async()=>{let call;const fetchMock=async(url,init)=>{call={url:String(url),init};return new Response(JSON.stringify({data:[]}),{status:200,headers:{'X-PublicAPI-Credits':'123','X-RateLimit-Remaining':'41','X-RateLimit-Reset':'999'}})};const c=new SeamlessRestClient('secret','https://api.test/v1',1000,fetchMock);const r=await c.getCredits();const u=new URL(call.url);assert.equal(u.pathname,'/v1/contacts');assert.match(u.searchParams.get('startDate'),/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);assert.match(u.searchParams.get('endDate'),/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);assert.equal(r.creditsRemaining,123);assert.ok(r.observedAt)});

test('poll uses returned request IDs as comma-separated query',async()=>{let url;const c=new SeamlessRestClient('x','https://api.test/v1',1000,async u=>{url=String(u);return new Response(JSON.stringify({success:true,data:[]}),{status:200})});await c.pollContactResearch(['a','b']);assert.equal(url,'https://api.test/v1/contacts/research/poll?requestIds=a%2Cb')});

test('lookup returns only the exact LinkedIn URL match and hides unrelated free results',async()=>{const store=new MemoryStore();let searches=0;const rest={searchContactsByName:async(name,limit)=>{searches++;assert.equal(name,'Jane Smith');assert.equal(limit,50);return{creditsRemaining:10,observedAt:'2026-09-07T18:00:00Z',data:{data:[{searchResultId:'wrong',name:'Jane Smith',company:'Other',title:'VP',liUrl:'https://www.linkedin.com/in/jane-smith-other/'},{searchResultId:'exact',name:'Jane Smith',company:'Acme',title:'Director',liUrl:'https://www.linkedin.com/in/jane-smith-1234/'}]}}},getCredits:async()=>({creditsRemaining:10})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup('https://www.linkedin.com/in/jane-smith-1234/');assert.equal(searches,1);assert.equal(r.searchUsedResearchCredits,false);assert.equal(r.exactFreeMatch,true);assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].searchResultId,'exact');assert.equal(r.candidates[0].company,'Acme');assert.equal(r.possibleMatches.length,0);assert.equal(r.routeSearches[0].creditsRemaining,10)});

test('lookup does not dump name matches when no exact LinkedIn URL was returned',async()=>{const store=new MemoryStore();const rest={searchContactsByName:async()=>({creditsRemaining:10,observedAt:'now',data:{data:[{searchResultId:'a',name:'Jane Smith',company:'Alpha',liUrl:'https://www.linkedin.com/in/jane-smith-a/'},{searchResultId:'b',name:'Jane Smith',company:'Beta',liUrl:'https://www.linkedin.com/in/jane-smith-b/'}]}}),getCredits:async()=>({creditsRemaining:10})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup('https://www.linkedin.com/in/jane-smith-1234/');assert.equal(r.exactFreeMatch,false);assert.equal(r.candidates.length,0);assert.equal(r.possibleMatches.length,2);assert.equal(r.directFallback,true)});


test('free lookup follows Seamless nextToken pages until the exact LinkedIn URL is found',async()=>{const store=new MemoryStore();const calls=[];const rest={searchContactsByName:async(name,limit,nextToken)=>{calls.push(nextToken);if(!nextToken)return{creditsRemaining:10,observedAt:'p1',data:{data:[{searchResultId:'wrong',name:'Jane Smith',company:'Other',liUrl:'https://www.linkedin.com/in/jane-smith-other/'}],supplementalData:{nextToken:'page2'}}};return{creditsRemaining:10,observedAt:'p2',data:{data:[{searchResultId:'exact',name:'Jane Smith',company:'Acme',liUrl:'https://www.linkedin.com/in/jane-smith-1234/'}],supplementalData:{nextToken:'page3'}}}},getCredits:async()=>({creditsRemaining:10})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup('https://www.linkedin.com/in/jane-smith-1234/');assert.deepEqual(calls,[null,'page2']);assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].searchResultId,'exact');assert.equal(r.routeSearches[0].pagesScanned,2)});

test('lookup uses cached completed result without a provider search',async()=>{const store=new MemoryStore();const url='https://www.linkedin.com/in/jane-smith/';const key=researchKey(url);store.jobs.set(key,{mode:'direct-linkedin-rest',status:'done',normalizedUrl:url,researchKey:key,createdAt:1,data:{fullName:'Jane',linkedinUrl:url}});let calls=0;const rest={searchContactsByName:async()=>{calls++},getCredits:async()=>({creditsRemaining:9})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup(url);assert.equal(r.cached,true);assert.equal(r.job.data.fullName,'Jane');assert.equal(calls,0)});

test('opaque slug avoids blind search and offers direct fallback',async()=>{const store=new MemoryStore();let calls=0;const rest={searchContactsByName:async()=>{calls++},getCredits:async()=>({creditsRemaining:9})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.lookup('https://www.linkedin.com/in/jsmith123/');assert.equal(calls,0);assert.equal(r.directFallback,true);assert.equal(r.freeSearchAvailable,false)});

test('two concurrent candidate enrichments submit exactly one research request',async()=>{const store=new MemoryStore();let calls=0;let release;const gate=new Promise(r=>release=r);const rest={researchSearchResult:async id=>{calls++;assert.equal(id,'s1');await gate;return{data:{requestIds:['req']},creditsRemaining:8}},getCredits:async()=>({creditsRemaining:8})};const svc=new EnrichmentService(cfg,store,rest);const input={searchResultId:'s1',linkedinUrl:'https://www.linkedin.com/in/jane/',candidate:{name:'Jane',company:'Acme'}};const p1=svc.startResearch(input);await new Promise(r=>setImmediate(r));const p2=svc.startResearch(input);release();const [a,b]=await Promise.all([p1,p2]);assert.equal(calls,1);assert.equal(a.status,'processing');assert.ok(['submitting','processing'].includes(b.status))});

test('definitive research rejection releases claim so operator can retry',async()=>{const store=new MemoryStore();let calls=0;const rest={researchSearchResult:async()=>{calls++;if(calls===1)throw new SeamlessRestError(422,'insufficientCredits','no credits');return{data:{requestIds:['ok']},creditsRemaining:5}},getCredits:async()=>({creditsRemaining:5})};const svc=new EnrichmentService(cfg,store,rest);const input={searchResultId:'s1',linkedinUrl:'https://www.linkedin.com/in/jane/'};await assert.rejects(()=>svc.startResearch(input),/no credits/);assert.equal(store.jobs.size,0);const r=await svc.startResearch(input);assert.equal(r.status,'processing');assert.equal(calls,2)});

test('uncertain timeout is saved and never auto-resubmitted',async()=>{const store=new MemoryStore();let calls=0;const rest={researchSearchResult:async()=>{calls++;throw new SeamlessRestError(504,'TIMEOUT','timeout')},getCredits:async()=>({creditsRemaining:5})};const svc=new EnrichmentService(cfg,store,rest);const input={searchResultId:'s1',linkedinUrl:'https://www.linkedin.com/in/jane/'};await assert.rejects(()=>svc.startResearch(input),/timeout/);const second=await svc.startResearch(input);assert.equal(second.status,'needs_review');assert.equal(calls,1)});

test('poll by searchResultId preserves selected identity and caches enriched data',async()=>{const store=new MemoryStore();store.jobs.set('s1',{mode:'search-result-rest',status:'processing',normalizedUrl:'https://www.linkedin.com/in/jane/',researchKey:'s1',searchResultId:'s1',selectedCandidate:{name:'Jane Smith',company:'Acme',title:'Director'},createdAt:1,requestIds:['req']});const rest={pollContactResearch:async()=>({creditsRemaining:7,observedAt:'2026-09-07T18:00:00Z',data:{data:[{requestId:'req',status:'done',contact:{fullName:'Jane Smith',email:'jane@example.com',contactPhone1:'+1555',company:'Acme',title:'Director',lIProfileUrl:'https://www.linkedin.com/in/jane/'}}]}}),getCredits:async()=>({creditsRemaining:7})};const svc=new EnrichmentService(cfg,store,rest);const r=await svc.pollResearch({searchResultId:'s1'});assert.equal(r.status,'done');assert.equal(r.selectedCandidate.company,'Acme');assert.equal(r.data.email,'jane@example.com');assert.equal((await store.getResearch('s1')).status,'done')});

test('status reports search-first REST architecture and provider credit snapshot',async()=>{const store=new MemoryStore();const svc=new EnrichmentService(cfg,store,{getCredits:async()=>({creditsRemaining:44,rateLimitRemaining:59,rateLimitReset:1,observedAt:'2026-09-07T18:00:00Z'})});const r=await svc.status();assert.equal(r.architecture,'multi-org-search-first-rest');assert.equal(r.seamless.mcpRequired,false);assert.equal(r.credits.totalCreditsRemaining,44);assert.equal(r.credits.routes[0].observedAt,'2026-09-07T18:00:00Z')});

test('HTTP workspace is protected and research route passes selected candidate',async()=>{let researchInput;const fake={lookup:async u=>({linkedinUrl:u,candidates:[]}),startResearch:async i=>(researchInput=i,{status:'processing'}),pollResearch:async()=>({status:'done'}),status:async()=>({database:{status:'READY'},seamless:{status:'READY'}}),ready:async()=>{}};const old=process.env.APP_AUTH_TOKEN;process.env.APP_AUTH_TOKEN='pw';const server=http.createServer(createHandler(fake));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await fetch(base+'/workspace')).status,401);const res=await fetch(base+'/v1/person/research',{method:'POST',headers:{Authorization:'Bearer pw','Content-Type':'application/json'},body:JSON.stringify({linkedinUrl:'https://www.linkedin.com/in/jane/',searchResultId:'s1',routeId:'secondary',candidate:{name:'Jane',company:'Acme'}})});assert.equal(res.status,202);assert.equal(researchInput.searchResultId,'s1');assert.equal(researchInput.routeId,'secondary');assert.equal(researchInput.candidate.company,'Acme')}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.APP_AUTH_TOKEN;else process.env.APP_AUTH_TOKEN=old}});


test('multi-org credentials bind each key to its own egress proxy',()=>{const r=seamlessCredentials({SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://proxy-a:8080',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://proxy-b:8080',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'});assert.equal(r.routes.length,2);assert.deepEqual(r.routes.map(x=>[x.id,x.source,x.proxyUrl]),[['primary','SEAMLESS_API_KEY_PRIMARY','http://proxy-a:8080'],['secondary','SEAMLESS_API_KEY_SECONDARY','http://proxy-b:8080']]);assert.equal(r.requireUniqueEgress,true)});

test('strict unique egress refuses missing or duplicate proxy assignments',()=>{assert.throws(()=>seamlessCredentials({SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://same:8080',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'}),/Configure SEAMLESS_EGRESS_PROXY_SECONDARY/);assert.throws(()=>seamlessCredentials({SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://same:8080',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://same:8080',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'}),/same proxy URL/)});

test('route pool sums separate organization credits and verifies distinct public IPs',async()=>{const env={SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://a:1',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://b:2',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'};const data={primary:{credits:12,ip:'203.0.113.10'},secondary:{credits:7,ip:'203.0.113.11'}};const pool=new SeamlessRoutePool(cfg,env,route=>({getCredits:async()=>({creditsRemaining:data[route.id].credits,rateLimitRemaining:50,observedAt:'2026-09-07T20:00:00Z'}),getEgressIp:async()=>({ip:data[route.id].ip,observedAt:'2026-09-07T20:00:00Z'})}));const st=await pool.status();assert.equal(st.status,'READY');assert.equal(st.totalCreditsRemaining,19);assert.equal(st.organizationCount,2);assert.equal(st.uniqueEgressVerified,true);assert.deepEqual(st.routes.map(x=>x.egressIp),['203.0.113.10','203.0.113.11'])});

test('route pool rejects two keys that resolve to the same public egress IP in strict mode',async()=>{const env={SEAMLESS_API_KEY_PRIMARY:'p',SEAMLESS_API_KEY_SECONDARY:'s',SEAMLESS_EGRESS_PROXY_PRIMARY:'http://a:1',SEAMLESS_EGRESS_PROXY_SECONDARY:'http://b:2',SEAMLESS_REQUIRE_UNIQUE_EGRESS:'true'};const pool=new SeamlessRoutePool(cfg,env,route=>({getCredits:async()=>({creditsRemaining:5}),getEgressIp:async()=>({ip:'203.0.113.10'})}));await assert.rejects(()=>pool.assertUniqueEgress(),/same public IP/);const st=await pool.status();assert.equal(st.status,'ERROR');assert.equal(st.uniqueEgressVerified,false)});

test('free search merges the same person across organizations and chooses the healthier route option',async()=>{const store=new MemoryStore();const mk=(id,credits)=>({searchContactsByName:async()=>({creditsRemaining:credits,observedAt:'now',data:{data:[{searchResultId:`${id}-sr`,name:'Jane Smith',company:'Acme',title:'Director',liUrl:'https://www.linkedin.com/in/jane-smith/'}]}})});const routes=[{id:'primary',source:'SEAMLESS_API_KEY_PRIMARY',client:mk('p',3)},{id:'secondary',source:'SEAMLESS_API_KEY_SECONDARY',client:mk('s',20)}];const pool={size:2,routes,routeMap:new Map(routes.map(r=>[r.id,r])),assertUniqueEgress:async()=>true,status:async()=>({status:'READY',organizationCount:2,totalCreditsRemaining:23,routes:[]})};const svc=new EnrichmentService(cfg,store,null,pool);const r=await svc.lookup('https://www.linkedin.com/in/jane-smith/');assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].availableOrganizations,2);assert.equal(r.candidates[0].routeId,'secondary');assert.equal(r.candidates[0].searchResultId,'s-sr')});

test('research and polling remain pinned to the organization route that produced the searchResultId',async()=>{const store=new MemoryStore();let primaryResearch=0,secondaryResearch=0,secondaryPoll=0;const primary={researchSearchResult:async()=>{primaryResearch++;throw Error('wrong route')}};const secondary={researchSearchResult:async id=>{secondaryResearch++;assert.equal(id,'s-sr');return{data:{requestIds:['req2']},creditsRemaining:9,observedAt:'now'}},pollContactResearch:async ids=>{secondaryPoll++;assert.deepEqual(ids,['req2']);return{data:{data:[{requestId:'req2',status:'done',contact:{fullName:'Jane Smith',company:'Acme'}}]},creditsRemaining:8,observedAt:'now'}}};const routes=[{id:'primary',source:'SEAMLESS_API_KEY_PRIMARY',client:primary},{id:'secondary',source:'SEAMLESS_API_KEY_SECONDARY',client:secondary}];const pool={size:2,routes,routeMap:new Map(routes.map(r=>[r.id,r])),assertUniqueEgress:async()=>true,status:async()=>({status:'READY',organizationCount:2,totalCreditsRemaining:10,routes:[]})};const svc=new EnrichmentService(cfg,store,null,pool);const job=await svc.startResearch({linkedinUrl:'https://www.linkedin.com/in/jane-smith/',searchResultId:'s-sr',routeId:'secondary',candidate:{name:'Jane Smith',company:'Acme'}});assert.equal(job.routeId,'secondary');assert.equal(primaryResearch,0);assert.equal(secondaryResearch,1);const done=await svc.pollResearch({searchResultId:'s-sr'});assert.equal(done.status,'done');assert.equal(secondaryPoll,1);assert.equal(primaryResearch,0)});


test('credit totals never reuse a stale balance when the fresh provider header is missing',async()=>{let calls=0;const env={SEAMLESS_API_KEY_PRIMARY:'p'};const pool=new SeamlessRoutePool(cfg,env,()=>({getCredits:async()=>{calls++;return calls===1?{creditsRemaining:12,observedAt:'first'}:{creditsRemaining:null,observedAt:'second'}},getEgressIp:async()=>({ip:'203.0.113.10'})}));const first=await pool.status();assert.equal(first.totalCreditsRemaining,12);const second=await pool.status();assert.equal(second.status,'ERROR');assert.equal(second.totalCreditsRemaining,null);assert.equal(second.routes[0].creditsRemaining,null);assert.equal(second.routes[0].lastKnownCreditsRemaining,12)});

test('verified build fingerprint matches current source',()=>{const {sourceHash}=require('../scripts-build-info.cjs');const info=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/BUILD_INFO.json'),'utf8'));assert.equal(info.version,'34.0.0');assert.equal(info.sourceHash,sourceHash())});
