import test from 'node:test';
import assert from 'node:assert/strict';
import {linkedInSearchArguments as args} from '../dist/src/mcp/searchSchema.js';
const url='https://www.linkedin.com/in/example/';
test('supports exact existing field spelling',()=>assert.deepEqual(args({properties:{liProfileUrl:{type:'array'}}},url),{liProfileUrl:[url]}));
test('supports snake case and nullable strings',()=>assert.deepEqual(args({properties:{linkedin_profile_url:{anyOf:[{type:'string'},{type:'null'}]}}},url),{linkedin_profile_url:url}));
test('supports nested filters and local schema references',()=>assert.deepEqual(args({properties:{filters:{type:'object',properties:{linkedin_url:{$ref:'#/$defs/url'}}}},$defs:{url:{type:'array',items:{type:'string'}}}},url),{filters:{linkedin_url:[url]}}));
test('supports allOf without manufacturing extra filters',()=>assert.deepEqual(args({allOf:[{properties:{linkedinUrls:{type:'array'}}}]},url),{linkedinUrls:[url]}));
test('name and generic keyword filters are not proof of URL support',()=>assert.equal(args({properties:{fullname:{type:'array'},contactKeyword:{type:'string'}}},url),null));
test('recursive schemas terminate',()=>assert.equal(args({properties:{filter:{$ref:'#/$defs/recurse'}},$defs:{recurse:{type:'object',properties:{next:{$ref:'#/$defs/recurse'}}}}},url),null));
