'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const {loadConfig}=require('../config');const {EnrichmentService}=require('../http/enrichment');const {ProspectingService}=require('../prospecting/service');const {SeamlessRestError}=require('../seamless/restClient');const {logger}=require('../utils/logger');
const publicDir=path.resolve(__dirname,'public');
function safeEqual(a,b){const ab=Buffer.from(a),bb=Buffer.from(b);return ab.length===bb.length&&crypto.timingSafeEqual(ab,bb)}
function send(res,status,body,type='application/json; charset=utf-8'){const data=Buffer.isBuffer(body)?body:typeof body==='string'?Buffer.from(body):Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':type,'Content-Length':data.length,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(data)}
function sendFile(res,name,type){try{send(res,200,fs.readFileSync(path.join(publicDir,name)),type)}catch{send(res,404,{error:'Not found'})}}
async function jsonBody(req){let total=0,chunks=[];for await(const chunk of req){total+=chunk.length;if(total>32768)throw Object.assign(new Error('Request body too large.'),{status:413});chunks.push(chunk)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON request.'),{status:400})}}
function authenticated(req){const expected=(process.env.APP_AUTH_TOKEN||'').trim();if(!expected)return{ok:false,status:503,error:'Authentication is not configured'};const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer ')||!safeEqual(auth.slice(7),expected))return{ok:false,status:401,error:'Unauthorized'};return{ok:true}}
function loadBuildInfo(){const candidates=[path.resolve(__dirname,'../../BUILD_INFO.json'),path.resolve(process.cwd(),'dist/BUILD_INFO.json')];for(const f of candidates)try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{}return{version:'45.0.0',buildId:'dev'}}
function mapResearchError(error){
  const diagnostics=Array.isArray(error?.diagnosticTrace)?error.diagnosticTrace:(error?.diagnostic?[error.diagnostic]:[]);
  const extra=diagnostics.length?{diagnosticTrace:diagnostics}:{};
  if(error instanceof SeamlessRestError){if(error.code==='insufficientCredits')return[402,{error:error.message,code:error.code,...extra}];if(error.code==='missingLicense')return[403,{error:error.message,code:error.code,...extra}];if(error.status===401||error.status===403)return[502,{error:error.message,code:error.code,...extra}];if(error.status===429)return[503,{error:error.message,code:error.code,...extra}];if(error.status===422)return[422,{error:error.message,code:error.code,...extra}]}
  return[502,{error:error.message||String(error),...extra}]
}

function createHandler(providedService){const config=loadConfig();let service=providedService;const getService=()=>service??(service=new EnrichmentService(config));const prospecting=new ProspectingService();return async function handler(req,res){try{const url=new URL(req.url,'http://localhost');const pathname=url.pathname;if(req.method==='GET'&&(pathname==='/'||pathname==='/index.html'))return sendFile(res,'login.html','text/html; charset=utf-8');if(req.method==='GET'&&pathname==='/app.css')return sendFile(res,'app.css','text/css; charset=utf-8');if(req.method==='GET'&&pathname==='/login.js')return sendFile(res,'login.js','text/javascript; charset=utf-8');if(req.method==='GET'&&pathname==='/health'){const b=loadBuildInfo();return send(res,200,{status:'ok',version:b.version,buildId:b.buildId,architecture:'enrichment-plus-prospecting-linkedin-persistent-session-circuit-breaker'})}
      const auth=authenticated(req);if(!auth.ok)return send(res,auth.status,{error:auth.error});if(req.method==='POST'&&pathname==='/auth/login')return send(res,200,{authenticated:true});if(req.method==='GET'&&(pathname==='/workspace'||pathname==='/chatbox.html'))return sendFile(res,'chatbox.html','text/html; charset=utf-8');if(req.method==='GET'&&pathname==='/app.js')return sendFile(res,'app.js','text/javascript; charset=utf-8');if(req.method==='GET'&&pathname==='/ready'){try{await getService().ready();return send(res,200,{status:'ready'})}catch(error){return send(res,503,{status:'not_ready',error:error.message})}}
      if(req.method==='POST'&&pathname==='/v1/diagnostics/reset'){const body=await jsonBody(req);const result=getService().resetDiagnostics(typeof body.reason==='string'?body.reason:'manual');return send(res,200,{...result,build:loadBuildInfo()})}
      if(req.method==='POST'&&pathname==='/v1/diagnostics/event'){const body=await jsonBody(req);getService().recordClientEvent(typeof body.name==='string'?body.name:'client_event',body.details&&typeof body.details==='object'?body.details:{});return send(res,200,{ok:true})}
      if(req.method==='GET'&&pathname==='/v1/diagnostics/report'){const report=getService().diagnosticReport();return send(res,200,{...report,build:loadBuildInfo()})}
      if(req.method==='GET'&&pathname==='/status'){const reason=url.searchParams.get('reason')||'unspecified';return send(res,200,await getService().status({reason}))}
      if(req.method==='GET'&&pathname==='/v1/prospect/roles')return send(res,200,{groups:prospecting.roles(),capabilities:prospecting.capabilities()})
      if(req.method==='GET'&&pathname==='/v1/prospect/capabilities')return send(res,200,prospecting.capabilities())
      if(req.method==='POST'&&pathname==='/v1/prospect/start'){const body=await jsonBody(req);try{const result=prospecting.start({company:body.company,group:body.group,roleIds:Array.isArray(body.roleIds)?body.roleIds:[]});return send(res,202,result)}catch(error){return send(res,422,{error:error.message})}}
      if(req.method==='GET'&&pathname==='/v1/prospect/status'){const job=prospecting.status(url.searchParams.get('jobId'));if(!job)return send(res,404,{error:'Prospecting job not found.'});return send(res,200,job)}
      if(req.method==='POST'&&pathname==='/v1/person/lookup'){const body=await jsonBody(req);const linkedinUrl=typeof body.linkedinUrl==='string'?body.linkedinUrl.trim():'';if(!linkedinUrl)return send(res,400,{error:'Enter a LinkedIn person URL.'});try{return send(res,200,await getService().lookup(linkedinUrl,typeof body.targetCompany==='string'?body.targetCompany.trim():''))}catch(error){if(/LinkedIn|Invalid URL|profile URL/i.test(error.message||''))return send(res,422,{error:error.message});logger.error('http.person.lookup',{error:error.message});return send(res,502,{error:error.message})}}
      if(req.method==='POST'&&pathname==='/v1/person/research'){const body=await jsonBody(req);const linkedinUrl=typeof body.linkedinUrl==='string'?body.linkedinUrl.trim():'';if(!linkedinUrl)return send(res,400,{error:'linkedinUrl is required.'});try{const result=await getService().startResearch({linkedinUrl,targetCompany:typeof body.targetCompany==='string'?body.targetCompany.trim():'',routeId:body.routeId});return send(res,['processing','submitting'].includes(result.status)?202:200,result)}catch(error){const [status,payload]=mapResearchError(error);logger.warn('http.person.research',{status,error:error.message});return send(res,status,payload)}}
      if(req.method==='POST'&&pathname==='/v1/person/research/status'){const body=await jsonBody(req);const linkedinUrl=typeof body.linkedinUrl==='string'?body.linkedinUrl.trim():'';if(!linkedinUrl)return send(res,400,{error:'linkedinUrl is required.'});try{const result=await getService().pollResearch({linkedinUrl});if(result.status==='not_found')return send(res,404,{error:'No research job was found for this contact.'});return send(res,['processing','submitting'].includes(result.status)?202:200,result)}catch(error){const [status,payload]=mapResearchError(error);return send(res,status,payload)}}return send(res,404,{error:'Not found'});
    }catch(error){logger.error('http.unhandled_error',{message:error.message});return send(res,error.status||502,{error:error.message||'Server error'})}}}
module.exports={createHandler};
