'use strict';
const crypto=require('node:crypto');
const {seamlessCredential}=require('../config/credentials');
const {SeamlessRestClient,SeamlessRestError}=require('../seamless/restClient');
const {SupabaseStore}=require('../storage/supabase');
const {normalizeLinkedInUrl}=require('../utils/normalizeUrl');
function str(...values){for(const value of values)if(typeof value==='string'&&value.trim())return value.trim()}
function stringList(...values){return[...new Set(values.flatMap(v=>Array.isArray(v)?v:[v]).filter(v=>typeof v==='string'&&v.trim()).map(v=>v.trim()))]}
function researchKey(url){return`linkedin:${crypto.createHash('sha256').update(url).digest('hex')}`}
function parseContact(contact,fallbackUrl){const linkedinUrl=str(contact?.lIProfileUrl,contact?.liProfileUrl,contact?.linkedinUrl)||fallbackUrl;return{id:str(contact?.contactId,contact?.id),fullName:str(contact?.fullName,contact?.name)||[contact?.firstName,contact?.lastName].filter(Boolean).join(' '),firstName:str(contact?.firstName),lastName:str(contact?.lastName),title:str(contact?.title,contact?.jobTitle),company:str(contact?.company,contact?.companyName),email:str(contact?.email,contact?.email1),phone:str(contact?.contactPhone1,contact?.phone),linkedinUrl,department:str(contact?.department),seniority:str(contact?.seniority),alternateEmails:stringList(contact?.email2,contact?.email3,contact?.personalEmail),alternatePhones:stringList(contact?.contactPhone2,contact?.companyPhone1,contact?.companyPhone2,contact?.companyPhone3),companyDomain:str(contact?.companyDomain,contact?.website),companyLinkedInUrl:str(contact?.companyLIProfileUrl,contact?.companyLinkedInUrl),contactLocation:contact?.contactLocation&&typeof contact.contactLocation==='object'?contact.contactLocation:undefined,companyLocation:contact?.companyLocation&&typeof contact.companyLocation==='object'?contact.companyLocation:undefined,raw:contact&&typeof contact==='object'?contact:undefined}}
class EnrichmentService{
  constructor(config,store=new SupabaseStore(),rest=null){this.config=config;this.store=store;if(rest){this.rest=rest;this.keySource=(process.env.SEAMLESS_KEY_SOURCE||'injected').trim()||'injected'}else{const c=seamlessCredential();this.keySource=c.source;this.rest=new SeamlessRestClient(c.key,config.apiBaseUrl,config.requestTimeoutMs)}}
  publicJob(job){if(job?.status==='submitting'&&Date.now()-job.createdAt>120000)return{...job,status:'needs_review',message:'The original Seamless submission could not be confirmed. No automatic retry will be made.'};return job}
  async lookup(linkedinUrl){const url=normalizeLinkedInUrl(linkedinUrl);await this.store.ensurePerson(url);const key=researchKey(url);const exact=await this.store.getResearch(key);if(exact)return{linkedinUrl:url,researchKey:key,job:this.publicJob(exact),cached:exact.status==='done'};const legacy=await this.store.researchForPerson(url);const done=legacy.find(j=>j?.status==='done'&&j?.data);if(done){const migrated={mode:'direct-linkedin-rest',status:'done',normalizedUrl:url,researchKey:key,data:done.data,createdAt:done.createdAt||Date.now(),updatedAt:Date.now(),cached:true,creditsCharged:0};if(await this.store.claimResearch(key,url,migrated))return{linkedinUrl:url,researchKey:key,job:migrated,cached:true};return{linkedinUrl:url,researchKey:key,job:this.publicJob(await this.store.getResearch(key)),cached:true}}return{linkedinUrl:url,researchKey:key,job:null,cached:false,readyToEnrich:true}}
  async startResearch(linkedinUrl){const url=normalizeLinkedInUrl(linkedinUrl);await this.store.ensurePerson(url);const key=researchKey(url);const existing=await this.store.getResearch(key);if(existing)return{...this.publicJob(existing),cached:existing.status==='done',creditsCharged:existing.status==='done'?0:existing.creditsCharged??null};const claim={mode:'direct-linkedin-rest',status:'submitting',normalizedUrl:url,researchKey:key,createdAt:Date.now(),creditsCharged:null};if(!await this.store.claimResearch(key,url,claim)){const winner=await this.store.getResearch(key);if(!winner)throw new Error('Could not confirm the research state. No new Seamless request was submitted.');return this.publicJob(winner)}
    try{const response=await this.rest.researchLinkedIn(url);const requestIds=Array.isArray(response.data?.requestIds)?response.data.requestIds.filter(Boolean):[];const next=requestIds.length?{...claim,status:'processing',requestIds,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,creditsCharged:null}:{...claim,status:'needs_review',updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,message:'Seamless accepted the request but returned no request ID. Check Seamless before retrying.'};await this.store.saveResearch(key,next);return next}catch(error){if(error instanceof SeamlessRestError&&[400,401,403,404,422,429].includes(error.status)){await this.store.deleteResearch(key).catch(()=>{});throw error}const safe={...claim,status:'needs_review',updatedAt:Date.now(),creditsRemaining:error instanceof SeamlessRestError?error.creditsRemaining??null:null,message:error instanceof SeamlessRestError?`${error.message} No automatic retry was made.`:'The Seamless submission outcome is uncertain. No automatic retry was made.'};await this.store.saveResearch(key,safe).catch(()=>{});throw error}}
  async pollResearch(linkedinUrl){const url=normalizeLinkedInUrl(linkedinUrl);const key=researchKey(url);const job=await this.store.getResearch(key);if(!job)return{status:'not_found'};if(job.status!=='processing'||!job.requestIds?.length)return this.publicJob(job);const response=await this.rest.pollContactResearch(job.requestIds);const rows=Array.isArray(response.data?.data)?response.data.data:[];const row=rows.find(item=>job.requestIds.includes(item?.requestId))||rows[0];if(!row)return{...job,creditsRemaining:response.creditsRemaining,message:'Research is still processing.'};const providerStatus=String(row.status||'').toLowerCase();if(providerStatus==='done'){const data=row.contact?parseContact(row.contact,url):undefined;const next=data?{...job,status:'done',providerStatus,data,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining}:{...job,status:'needs_review',providerStatus,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,message:'Seamless marked research done but did not return a contact record. No new research was submitted.'};await this.store.saveResearch(key,next);return next}if(providerStatus==='duplicate'){const data=row.contact?parseContact(row.contact,url):undefined;const next=data?{...job,status:'done',providerStatus,data,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining}:{...job,status:'duplicate',providerStatus,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,message:row.message||'Seamless reports this contact was already researched. Do not resubmit it automatically.'};await this.store.saveResearch(key,next);return next}if(providerStatus==='missing'){const next={...job,status:'missing',providerStatus,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,message:row.message||'Seamless could not find this contact.'};await this.store.saveResearch(key,next);return next}if(providerStatus==='error'){const next={...job,status:'failed',providerStatus,updatedAt:Date.now(),creditsRemaining:response.creditsRemaining,message:row.message||'Seamless research failed.'};await this.store.saveResearch(key,next);return next}return{...job,providerStatus:providerStatus||job.providerStatus,creditsRemaining:response.creditsRemaining}}
  async ready(){await this.store.ready()}
  async status(){const result={architecture:'direct-linkedin-rest',keySource:this.keySource,database:{status:'ERROR'},seamless:{status:'CONFIGURED',transport:'REST',mcpRequired:false},credits:null};try{await this.store.ready();result.database={status:'READY'}}catch(error){result.database={status:'ERROR',error:error.message}}try{const credits=await this.rest.getCredits();result.seamless={status:'READY',transport:'REST',mcpRequired:false};result.credits=credits}catch(error){result.seamless={status:'ERROR',transport:'REST',mcpRequired:false,error:error.message}}return result}
}
module.exports={EnrichmentService,researchKey,parseContact};
