'use strict';
const {logger}=require('../utils/logger');
class SeamlessRestError extends Error{constructor(status,code,message,details,creditsRemaining=null){super(message);this.name='SeamlessRestError';this.status=status;this.code=code;this.details=details;this.creditsRemaining=creditsRemaining}}
function numericHeader(headers,name){const raw=headers.get(name);if(raw==null||raw.trim()==='')return null;const v=Number(raw);return Number.isFinite(v)?v:null}
function classify(status,body){const code=typeof body?.code==='string'?body.code:`HTTP_${status}`;const raw=[body?.msg,body?.message,body?.error?.message,body?.error].find(v=>typeof v==='string'&&v.trim());if(code==='insufficientCredits')return{code,message:'Seamless reports insufficient Public API research credits.'};if(code==='missingLicense')return{code,message:'This Seamless connection does not have an active Public API license.'};if(status===401)return{code,message:'Seamless rejected the API key. Check the selected Render secret.'};if(status===403)return{code,message:'Seamless refused this API key. Check Public API v1 access and group permissions.'};if(status===429)return{code,message:'Seamless rate limit reached. Retry after the provider reset window.'};if(status===422&&raw)return{code,message:`Seamless rejected the request: ${String(raw).slice(0,240)}`};if(status>=500)return{code,message:`Seamless is temporarily unavailable (HTTP ${status}).`};return{code,message:raw?String(raw).slice(0,240):`Seamless request failed (HTTP ${status}).`}}
class SeamlessRestClient{
  constructor(apiKey,baseUrl='https://api.seamless.ai/api/client/v1',timeoutMs=30000,fetchImpl=globalThis.fetch){if(!apiKey)throw new Error('Missing Seamless API key');this.apiKey=apiKey;this.baseUrl=baseUrl.replace(/\/$/,'');this.timeoutMs=timeoutMs;this.fetch=fetchImpl}
  async request(path,init={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetch(this.baseUrl+path,{...init,headers:{Accept:'application/json',Token:this.apiKey,...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers||{})},signal:controller.signal});const creditsRemaining=numericHeader(response.headers,'X-PublicAPI-Credits');const rateLimitRemaining=numericHeader(response.headers,'X-RateLimit-Remaining');const rateLimitReset=numericHeader(response.headers,'X-RateLimit-Reset');const text=await response.text();let body=null;if(text){try{body=JSON.parse(text)}catch{body={message:text.slice(0,240)}}}if(!response.ok){const c=classify(response.status,body);throw new SeamlessRestError(response.status,c.code,c.message,body?.data,creditsRemaining)}return{data:body,creditsRemaining,rateLimitRemaining,rateLimitReset}}catch(error){if(error?.name==='AbortError')throw new SeamlessRestError(504,'TIMEOUT',`Seamless REST request timed out after ${this.timeoutMs}ms.`);if(!(error instanceof SeamlessRestError))logger.warn('seamless.rest.request_failed',{path,message:error?.message||String(error)});throw error}finally{clearTimeout(timer)}}
  researchLinkedIn(linkedinUrl){return this.request('/contacts/research',{method:'POST',body:JSON.stringify({contacts:[{liProfileUrl:linkedinUrl}],skipDeduplicationCheck:false})})}
  pollContactResearch(requestIds){return this.request(`/contacts/research/poll?${new URLSearchParams({requestIds:requestIds.join(',')})}`,{method:'GET'})}
  async getCredits(){const r=await this.request('/contacts?page=1&limit=1',{method:'GET'});return{creditsRemaining:r.creditsRemaining,rateLimitRemaining:r.rateLimitRemaining,rateLimitReset:r.rateLimitReset}}
}
module.exports={SeamlessRestClient,SeamlessRestError};
