'use strict';
const {seamlessCredentials}=require('../config/credentials');
const {SeamlessRestClient}=require('./restClient');
class SeamlessRoutePool{
  constructor(config,env=process.env,clientFactory=null){
    const found=seamlessCredentials(env);this.requireUniqueEgress=found.requireUniqueEgress;this.checkUrl=(env.SEAMLESS_EGRESS_CHECK_URL||'https://api.ipify.org?format=json').trim();
    this.routes=found.routes.map((route,index)=>{const client=clientFactory?clientFactory(route,index):new SeamlessRestClient(route.key,config.apiBaseUrl,config.requestTimeoutMs,null,{proxyUrl:route.proxyUrl,routeId:route.id,keySource:route.source});return{...route,client,lastCredits:null,lastCreditsAt:null,lastEgressIp:null,lastEgressAt:null}});
    this.routeMap=new Map(this.routes.map(r=>[r.id,r]));this.cursor=0;this.egressCacheAt=0;
  }
  get size(){return this.routes.length}
  clientFor(routeId){const route=this.routeMap.get(routeId)||this.routes[0];if(!route)throw new Error('No Seamless route is configured.');return route.client}
  async probeRoute(route,{egress=true}={}){let credits=null,error=null,egressIp=route.lastEgressIp,egressObservedAt=route.lastEgressAt;try{credits=await route.client.getCredits();if(Number.isFinite(credits.creditsRemaining)){route.lastCredits=credits.creditsRemaining;route.lastCreditsAt=credits.observedAt}else error='Seamless did not return X-PublicAPI-Credits on the fresh authenticated response.'}catch(e){error=e.message||String(e)}if(egress){try{const x=await route.client.getEgressIp(this.checkUrl);egressIp=x.ip;egressObservedAt=x.observedAt;route.lastEgressIp=egressIp;route.lastEgressAt=egressObservedAt}catch(e){if(this.requireUniqueEgress)error=error?`${error}; egress: ${e.message}`:`Egress check failed: ${e.message}`}}
    return{id:route.id,keySource:route.source,proxyConfigured:Boolean(route.proxyUrl),creditsRemaining:Number.isFinite(credits?.creditsRemaining)?credits.creditsRemaining:null,lastKnownCreditsRemaining:route.lastCredits,rateLimitRemaining:credits?.rateLimitRemaining??null,rateLimitReset:credits?.rateLimitReset??null,observedAt:Number.isFinite(credits?.creditsRemaining)?credits.observedAt:null,egressIp,egressObservedAt,status:error?'ERROR':'READY',error};}
  async status(){const items=await Promise.all(this.routes.map(r=>this.probeRoute(r)));const valid=items.filter(x=>x.status==='READY');const total=valid.reduce((sum,x)=>sum+(Number.isFinite(x.creditsRemaining)?x.creditsRemaining:0),0);const known=valid.filter(x=>Number.isFinite(x.creditsRemaining)).length;const ips=items.map(x=>x.egressIp).filter(Boolean);const uniqueIps=new Set(ips);const uniqueEgressOk=!this.requireUniqueEgress||(items.every(x=>x.proxyConfigured&&x.egressIp)&&uniqueIps.size===items.length);return{status:valid.length===items.length&&uniqueEgressOk?'READY':'ERROR',routes:items,totalCreditsRemaining:known?total:null,organizationCount:items.length,uniqueEgressRequired:this.requireUniqueEgress,uniqueEgressVerified:items.length<=1?true:(ips.length===items.length&&uniqueIps.size===items.length),error:!uniqueEgressOk?'Configured Seamless routes are not verified on distinct egress IPs.':undefined};}
  async assertUniqueEgress(){if(!this.requireUniqueEgress||this.routes.length<=1)return true;const now=Date.now();if(now-this.egressCacheAt<300000){const ips=this.routes.map(r=>r.lastEgressIp);if(ips.every(Boolean)&&new Set(ips).size===ips.length)return true;}const probes=await Promise.all(this.routes.map(async r=>{if(!r.proxyUrl)throw new Error(`${r.source} has no dedicated egress proxy configured.`);const x=await r.client.getEgressIp(this.checkUrl);r.lastEgressIp=x.ip;r.lastEgressAt=x.observedAt;return x.ip;}));this.egressCacheAt=now;if(new Set(probes).size!==probes.length)throw new Error('Unique egress check failed: two Seamless API keys currently exit through the same public IP.');return true;}
  async chooseSearchRoute(){await this.assertUniqueEgress();const route=this.routes[this.cursor%this.routes.length];this.cursor=(this.cursor+1)%this.routes.length;return route;}
  async chooseResearchRoute(){await this.assertUniqueEgress();const statuses=await Promise.all(this.routes.map(r=>this.probeRoute(r,{egress:false})));const ranked=statuses.filter(s=>s.status==='READY').sort((a,b)=>(b.creditsRemaining??-1)-(a.creditsRemaining??-1));const chosen=ranked[0]?this.routeMap.get(ranked[0].id):this.routes[0];if(!chosen)throw new Error('No healthy Seamless API route is available.');return chosen;}
}
module.exports={SeamlessRoutePool};
