'use strict';
const crypto=require('node:crypto');
const {getRoles,publicRoleGroups}=require('./roles');
const {runEngine,configuredEngines}=require('./searchEngines');
const {LinkedInDirectCollector}=require('./linkedinDirect');

const LINKEDIN_PERSON=/^https?:\/\/(?:[a-z]{2,3}\.)?linkedin\.com\/(?:in|pub)\/[^/?#]+/i;
const NEGATIVE_CURRENT=/\b(former|previously|ex[- ]|past role|left\s+|until\s+20\d\d|20\d\d\s*[-–]\s*20\d\d)\b/i;
const STOP=new Set('of the and or in for to a an information technology technologies manager management director head vice president chief officer senior global regional corporate group lead leader it ict is mis'.split(' '));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function norm(s=''){return String(s).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9+]+/g,' ').replace(/\s+/g,' ').trim()}
function tokens(s){return norm(s).split(' ').filter(x=>x&&(!STOP.has(x)||x==='cio'||x==='cto'||x==='ceo'))}
function canonicalLinkedIn(raw){try{const m=String(raw||'').match(LINKEDIN_PERSON);if(!m)return null;const u=new URL(m[0]);u.protocol='https:';u.hostname='www.linkedin.com';u.search='';u.hash='';u.pathname=u.pathname.replace(/\/+$/,'');return u.toString()}catch{return null}}
function nameFromLinkedIn(url,title='',explicit=''){if(explicit&&explicit.length<120)return explicit.trim();const fromTitle=String(title).replace(/\s*\|\s*LinkedIn.*$/i,'').split(/\s[-–—]\s/)[0].trim();if(fromTitle&&fromTitle.length<100&&!/^linkedin$/i.test(fromTitle))return fromTitle;try{return decodeURIComponent(new URL(url).pathname.split('/').filter(Boolean).pop()).replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}catch{return''}}
function titleFromResult(title='',snippet='',company='',explicit=''){if(explicit)return String(explicit).trim();const clean=String(title).replace(/\s*\|\s*LinkedIn.*$/i,'').trim();const parts=clean.split(/\s[-–—]\s/).map(x=>x.trim()).filter(Boolean);if(parts.length>=2){const candidate=parts[1];if(!company||!sameCompany(candidate,company))return candidate;const rest=parts.slice(1).join(' — ');if(!sameCompany(rest,company))return rest}const s=String(snippet);const m=s.match(/(?:^|[.·|])\s*([^.!|]{3,100}?(?:manager|director|head|president|officer|administrator|admin|founder|owner|devops|security|infrastructure|data|cloud|operations)[^.!|]{0,50})(?:[.·|]|$)/i);return m?m[1].trim():''}
function sameCompany(text,company){const a=norm(text),b=norm(company);return Boolean(a&&b&&(a.includes(b)||b.includes(a)))}
function aliasScore(text,role){const n=norm(text);let best=0,bestAlias='';for(const alias of role.aliases){const a=norm(alias);if(!a)continue;if(n.includes(a)){const score=a===norm(role.label)?100:98;if(score>best){best=score;bestAlias=alias}continue}const at=tokens(alias),tt=new Set(tokens(text));if(!at.length)continue;const hit=at.filter(x=>tt.has(x)).length;const score=Math.round(100*hit/at.length);if(score>best&&score>=60){best=Math.min(score,90);bestAlias=alias}}return{score:best,alias:bestAlias}}
function currentScore(result,company){if(result.direct===true){let score=94;if(result.snippet&&sameCompany(result.snippet,company))score=97;if(NEGATIVE_CURRENT.test(`${result.title||''} ${result.snippet||''}`))score-=40;return Math.max(5,Math.min(99,score))}const text=`${result.title||''} ${result.snippet||''}`;let score=sameCompany(text,company)?82:58;if(NEGATIVE_CURRENT.test(text))score-=45;if(/\b(current|currently|present|at)\b/i.test(text)&&sameCompany(text,company))score+=8;return Math.max(5,Math.min(99,score))}
function queryForAliases(company,role,aliases,batch=1,depth=0){return{roleId:role.id,roleLabel:role.label,batch,depth,aliases,query:`site:linkedin.com/in "${company.replace(/"/g,'')}" (${aliases.map(a=>`"${a.replace(/"/g,'')}"`).join(' OR ')})`}}
function makeQueries(company,role){const aliases=role.aliases;const chunks=[];const size=Math.max(1,Number(process.env.PROSPECT_ALIAS_CHUNK_SIZE||6));for(let i=0;i<aliases.length;i+=size)chunks.push(aliases.slice(i,i+size));const maxChunks=Math.max(1,Number(process.env.PROSPECT_MAX_ALIAS_CHUNKS_PER_ROLE||4));return chunks.slice(0,maxChunks).map((c,i)=>queryForAliases(company,role,c,i+1,0))}
function mergeCandidate(map,result,company,role,queryMeta){const linkedinUrl=canonicalLinkedIn(result.url);if(!linkedinUrl)return false;const text=`${result.title||''} ${result.snippet||''} ${result.headline||''}`;const match=result.direct&&result.matchedAlias?{score:Math.max(98,aliasScore(text,role).score),alias:result.matchedAlias}:aliasScore(text,role);if(match.score<55)return false;const id=crypto.createHash('sha1').update(linkedinUrl).digest('hex').slice(0,16);let row=map.get(linkedinUrl);if(!row){row={id,linkedinUrl,name:nameFromLinkedIn(linkedinUrl,result.title,result.name),title:titleFromResult(result.title,result.snippet,company,result.headline),company,location:result.location||null,roleId:role.id,roleLabel:role.label,roleConfidence:match.score,currentEmploymentConfidence:currentScore(result,company),matchedAlias:match.alias,sources:[],sourceCount:0,directLinkedIn:Boolean(result.direct)};map.set(linkedinUrl,row)}else{if(match.score>row.roleConfidence){row.roleConfidence=match.score;row.roleId=role.id;row.roleLabel=role.label;row.matchedAlias=match.alias}row.currentEmploymentConfidence=Math.max(row.currentEmploymentConfidence,currentScore(result,company));if(!row.title)row.title=titleFromResult(result.title,result.snippet,company,result.headline);if(!row.location&&result.location)row.location=result.location;if(result.direct)row.directLinkedIn=true}
  const engine=result.engine||'unknown';const key=`${engine}|${result.url}|${queryMeta.query}`;if(!row.sources.some(s=>s.key===key)){row.sources.push({key,engine,query:queryMeta.query,title:result.title,snippet:result.snippet,url:result.url,roleId:role.id,roleLabel:role.label,partition:queryMeta.partition||null});row.sourceCount=row.sources.length}return true}
function safeJob(j){return{jobId:j.jobId,status:j.status,company:j.company,group:j.group,selectedRoles:j.selectedRoles,createdAt:j.createdAt,updatedAt:j.updatedAt,progress:j.progress,summary:j.summary,results:['done','running','stopped'].includes(j.status)?j.results:[],errors:j.errors.slice(-50),capabilities:j.capabilities}}
class ProspectingService{
  constructor({engineRunner=runEngine,engines=configuredEngines,directCollector=new LinkedInDirectCollector()}={}){this.jobs=new Map();this.engineRunner=engineRunner;this.engines=engines;this.directCollector=directCollector;}
  roles(){return publicRoleGroups()}
  capabilities(){return{publicEngines:this.engines(),linkedinDirect:this.directCollector.capabilities()}}
  start({company,group='flagged',roleIds=[]}){company=String(company||'').trim();if(company.length<2)throw new Error('Enter a company name.');if(!['flagged','not_flagged'].includes(group))throw new Error('Choose Flagged or Not Flagged roles.');const roles=getRoles(roleIds,group);if(!roles.length)throw new Error('Select at least one role.');const jobId=crypto.randomUUID();const capabilities=this.capabilities();const job={jobId,status:'running',cancelRequested:false,company,group,selectedRoles:roles.map(r=>({id:r.id,label:r.label,aliasCount:r.aliases.length})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),progress:{stage:'Planning searches',stopRequested:false,queriesPlanned:0,queriesCompleted:0,engineCallsPlanned:0,engineCallsCompleted:0,candidatesSeen:0,uniqueEmployees:0,currentRole:null,currentEngine:null,adaptivePartitions:0,saturatedQueries:0,linkedinDirect:{configured:capabilities.linkedinDirect.configured,status:capabilities.linkedinDirect.configured?'queued':'not_configured',transport:capabilities.linkedinDirect.transport||null,requests:0,buckets:0,partitions:0,partialBuckets:0,company:null}},summary:null,results:[],errors:[],capabilities};this.jobs.set(jobId,job);this.#run(job,roles).catch(e=>{job.status='failed';job.updatedAt=new Date().toISOString();job.errors.push({at:job.updatedAt,message:e.message,code:e.code||null});job.progress.stage='Failed'});return safeJob(job)}
  status(jobId){const j=this.jobs.get(String(jobId||''));return j?safeJob(j):null}
  stop(jobId){const j=this.jobs.get(String(jobId||''));if(!j)return null;if(j.status==='running'){j.cancelRequested=true;j.progress.stopRequested=true;j.progress.stage='Stopping prospecting';j.updatedAt=new Date().toISOString()}return safeJob(j)}
  async #run(job,roles){const candidates=new Map();const resort=()=>{job.results=[...candidates.values()].sort((a,b)=>(b.currentEmploymentConfidence+b.roleConfidence+b.sourceCount*3+Number(b.directLinkedIn)*4)-(a.currentEmploymentConfidence+a.roleConfidence+a.sourceCount*3+Number(a.directLinkedIn)*4));job.progress.uniqueEmployees=job.results.length;job.updatedAt=new Date().toISOString()};
    const publicPromise=this.#runPublic(job,roles,candidates,resort);
    const directPromise=this.#runDirect(job,roles,candidates,resort);
    await Promise.allSettled([publicPromise,directPromise]);
    job.results=[...candidates.values()].map(r=>({...r,sources:r.sources.map(({key,...x})=>x)})).sort((a,b)=>(b.currentEmploymentConfidence+b.roleConfidence+b.sourceCount*3+Number(b.directLinkedIn)*4)-(a.currentEmploymentConfidence+a.roleConfidence+a.sourceCount*3+Number(a.directLinkedIn)*4));job.progress.uniqueEmployees=job.results.length;job.progress.currentRole=null;job.progress.currentEngine=null;job.progress.stage=job.cancelRequested?'Stopped by user':'Complete';job.summary={employees:job.results.length,highConfidence:job.results.filter(r=>r.roleConfidence>=90&&r.currentEmploymentConfidence>=80).length,likelyCurrent:job.results.filter(r=>r.currentEmploymentConfidence>=80).length,directLinkedIn:job.results.filter(r=>r.directLinkedIn).length,sourceCounts:job.results.reduce((a,r)=>{for(const s of r.sources)a[s.engine]=(a[s.engine]||0)+1;return a},{}),queries:job.progress.queriesCompleted,engineCalls:job.progress.engineCallsCompleted,adaptivePartitions:job.progress.adaptivePartitions,saturatedQueries:job.progress.saturatedQueries,linkedinDirect:job.progress.linkedinDirect,engines:this.engines()};job.status=job.cancelRequested?'stopped':'done';job.updatedAt=new Date().toISOString()}
  async #runPublic(job,roles,candidates,resort){const engines=this.engines();const plan=roles.flatMap(role=>makeQueries(job.company,role).map(q=>({...q,role})));const maxQueries=Math.max(1,Number(process.env.PROSPECT_MAX_QUERIES||60));const clipped=plan.slice(0,maxQueries);job.progress.queriesPlanned=clipped.length;const limit=Math.max(5,Math.min(50,Number(process.env.PROSPECT_RESULTS_PER_QUERY||30)));const maxDepth=Math.max(0,Math.min(5,Number(process.env.PROSPECT_ADAPTIVE_SPLIT_DEPTH||3)));const maxCalls=Math.max(engines.length,Number(process.env.PROSPECT_MAX_ENGINE_CALLS||Math.max(120,clipped.length*engines.length*3)));let callsScheduled=clipped.length*engines.length;job.progress.engineCallsPlanned+=callsScheduled;job.progress.stage='Discovering LinkedIn profiles';const tasks=[];for(const q of clipped)for(const engine of engines)tasks.push({q,engine});let index=0;const concurrency=Math.max(1,Math.min(8,Number(process.env.PROSPECT_CONCURRENCY||4)));
    const runOne=async({q,engine})=>{if(job.cancelRequested)return;job.progress.currentRole=q.roleLabel;job.progress.currentEngine=engine;let rows=[];let children=[];try{rows=await this.engineRunner(engine,q.query,limit);if(job.cancelRequested)return;job.progress.candidatesSeen+=rows.length;for(const r of rows)mergeCandidate(candidates,r,job.company,q.role,q);if(rows.length>=limit){job.progress.saturatedQueries++;if(q.aliases.length>1&&q.depth<maxDepth&&callsScheduled+2<=maxCalls){const mid=Math.ceil(q.aliases.length/2),parts=[q.aliases.slice(0,mid),q.aliases.slice(mid)].filter(x=>x.length);children=parts.map(aliases=>({q:{...queryForAliases(job.company,q.role,aliases,q.batch,q.depth+1),role:q.role,partition:`alias_split_${q.depth+1}`},engine}));callsScheduled+=children.length;job.progress.engineCallsPlanned+=children.length;job.progress.adaptivePartitions++;}}}catch(error){job.errors.push({at:new Date().toISOString(),engine,role:q.roleLabel,query:q.query,message:error.message})}job.progress.engineCallsCompleted++;job.progress.queriesCompleted++;resort();for(const child of children){if(job.cancelRequested)break;await runOne(child)}};
    const workers=Array.from({length:concurrency},async()=>{while(true){if(job.cancelRequested)return;const i=index++;if(i>=tasks.length)return;await runOne(tasks[i])}});await Promise.all(workers)}
  async #runDirect(job,roles,candidates,resort){if(!this.directCollector.configured())return;job.progress.linkedinDirect.status='running';job.progress.currentEngine='linkedin-direct';try{const result=await this.directCollector.discover({company:job.company,roles,shouldStop:()=>job.cancelRequested,onEvent:e=>{const d=job.progress.linkedinDirect;if(e.type==='company_resolved')d.company=e.company;if(e.type==='session_state')d.session=e.session;if(e.type==='direct_stage')d.stage=e.stage;if(e.type==='failure'){d.stage=e.stage||d.stage;d.error=e.message;d.code=e.code||null;if(Number.isFinite(e.requests))d.requests=e.requests;d.session=e.session||d.session}if(e.type==='stopped'){d.status='stopped';d.stage='Stopped by user'};if(e.type==='request'){d.requests=e.requestNo||d.requests;d.lastTotal=e.total;d.lastResults=e.results;d.session=e.session||d.session}if(e.type==='partition'){d.partitions++;job.progress.adaptivePartitions++}if(e.type==='partial_bucket')d.partialBuckets++;if(e.type==='alias_start'){job.progress.currentRole=e.roleLabel;d.currentAlias=e.alias}if(e.type==='halt'){d.status='halted';d.haltCode=e.code;d.haltMessage=e.message}job.updatedAt=new Date().toISOString()},onRow:r=>{const role=roles.find(x=>x.id===r.roleId);if(!role)return;mergeCandidate(candidates,r,job.company,role,{query:`LinkedIn currentCompany=${r.company||job.company}; title=${r.matchedAlias}`,partition:r.networkDepth?`network:${r.networkDepth}`:'base'});job.progress.candidatesSeen++;resort()}});Object.assign(job.progress.linkedinDirect,result.stats||{});job.progress.linkedinDirect.configured=result.configured;job.progress.linkedinDirect.status=job.cancelRequested?'stopped':(job.progress.linkedinDirect.status==='halted'?'halted':'done');resort()}catch(error){job.progress.linkedinDirect.status='failed';job.progress.linkedinDirect.error=error.message;job.progress.linkedinDirect.code=error.code||null;job.errors.push({at:new Date().toISOString(),engine:'linkedin-direct',message:error.message,code:error.code||null});job.updatedAt=new Date().toISOString()}}
}
module.exports={ProspectingService,canonicalLinkedIn,aliasScore,currentScore,makeQueries,queryForAliases,mergeCandidate};
